version: '3.7'

services:
  db:
    container_name: main_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - web_net
  web:
    container_name: main_app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    command:
      sh -c "
      python /usr/src/app/manage.py loadscript with_clear &&
      python /usr/src/app/manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db
    networks:
      - web_net

volumes:
  postgres_data:
networks:
  web_net:
    name: web_net